# Form implementation generated from reading ui file 'D:\Documents\KTLT\FinalTerm\ui\Admin\AddClass.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddClassDialog(object):
    def setupUi(self, AddClassDialog):
        AddClassDialog.setObjectName("AddClassDialog")
        AddClassDialog.resize(1000, 600)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=AddClassDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 981, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setStyleSheet("color: rgb(0, 0, 90);\n"
"font: 5000 22pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(7)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_18 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 55))
        self.label_18.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_12.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 55))
        self.label_19.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_12.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 55))
        self.label_20.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_12.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 55))
        self.label_21.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_12.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 55))
        self.label_22.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.label_22.setObjectName("label_22")
        self.verticalLayout_12.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 55))
        self.label_23.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_12.addWidget(self.label_23)
        self.horizontalLayout_2.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(7)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.lineEdit_id_4 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_id_4.setSizePolicy(sizePolicy)
        self.lineEdit_id_4.setMaximumSize(QtCore.QSize(16777215, 55))
        self.lineEdit_id_4.setSizeIncrement(QtCore.QSize(0, 10))
        self.lineEdit_id_4.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 20px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 20px; /* Chừa khoảng trống bên phải */\n"
"}")
        self.lineEdit_id_4.setObjectName("lineEdit_id_4")
        self.verticalLayout_13.addWidget(self.lineEdit_id_4)
        self.lineEdit_fullname_4 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_fullname_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_fullname_4.setSizePolicy(sizePolicy)
        self.lineEdit_fullname_4.setMaximumSize(QtCore.QSize(16777215, 55))
        self.lineEdit_fullname_4.setSizeIncrement(QtCore.QSize(0, 10))
        self.lineEdit_fullname_4.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 20px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 20px; /* Chừa khoảng trống bên phải */\n"
"}")
        self.lineEdit_fullname_4.setObjectName("lineEdit_fullname_4")
        self.verticalLayout_13.addWidget(self.lineEdit_fullname_4)
        self.lineEdit_mail_4 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_mail_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_mail_4.setSizePolicy(sizePolicy)
        self.lineEdit_mail_4.setMaximumSize(QtCore.QSize(16777215, 55))
        self.lineEdit_mail_4.setSizeIncrement(QtCore.QSize(0, 10))
        self.lineEdit_mail_4.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 20px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 20px; /* Chừa khoảng trống bên phải */\n"
"}")
        self.lineEdit_mail_4.setObjectName("lineEdit_mail_4")
        self.verticalLayout_13.addWidget(self.lineEdit_mail_4)
        self.lineEdit_mail_8 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_mail_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_mail_8.setSizePolicy(sizePolicy)
        self.lineEdit_mail_8.setMaximumSize(QtCore.QSize(16777215, 55))
        self.lineEdit_mail_8.setSizeIncrement(QtCore.QSize(0, 10))
        self.lineEdit_mail_8.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 20px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 20px; /* Chừa khoảng trống bên phải */\n"
"}")
        self.lineEdit_mail_8.setObjectName("lineEdit_mail_8")
        self.verticalLayout_13.addWidget(self.lineEdit_mail_8)
        self.lineEdit_mail_6 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_mail_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_mail_6.setSizePolicy(sizePolicy)
        self.lineEdit_mail_6.setMaximumSize(QtCore.QSize(16777215, 55))
        self.lineEdit_mail_6.setSizeIncrement(QtCore.QSize(0, 10))
        self.lineEdit_mail_6.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 20px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 20px; /* Chừa khoảng trống bên phải */\n"
"}")
        self.lineEdit_mail_6.setObjectName("lineEdit_mail_6")
        self.verticalLayout_13.addWidget(self.lineEdit_mail_6)
        self.pushButton_AssignStudent_2 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_AssignStudent_2.setMaximumSize(QtCore.QSize(16777215, 55))
        self.pushButton_AssignStudent_2.setStyleSheet("QPushButton {\n"
"    font: 5000 14pt \"Arial\"; /* Font Arial Black, size 12 */\n"
"    background-color: rgba(255,255,255,100); /* Màu nền đỏ đậm */\n"
"    color: rgb(0,0,90); /* Màu chữ trắng */\n"
"    border-radius: 20px;\n"
"    padding: 8px; /* Khoảng cách giữa chữ và viền */\n"
"    border: 4px solid rgba(255, 255,255, 200); /* Viền đỏ đậm */\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 100); /* Đổ bóng */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,0,90); /* Màu sáng hơn khi hover */\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0,9); /* Màu tối hơn khi nhấn */\n"
"    color: rgb(255,255,255);\n"
"    box-shadow: 1px 1px 5px rgba(0, 0, 0, 150); /* Giảm bóng khi nhấn */\n"
"}")
        self.pushButton_AssignStudent_2.setObjectName("pushButton_AssignStudent_2")
        self.verticalLayout_13.addWidget(self.pushButton_AssignStudent_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Home = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_Home.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_Home.setMaximumSize(QtCore.QSize(16777215, 45))
        self.pushButton_Home.setStyleSheet("QPushButton {\n"
"    font: 5000 14pt \"Arial\"; /* Font Arial Black, size 12 */\n"
"    background-color: rgba(170,0,0,150); /* Màu nền đỏ đậm */\n"
"    color: rgb(255,255,255); /* Màu chữ trắng */\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    padding: 4px; /* Khoảng cách giữa chữ và viền */\n"
"    border: 4px solid rgba(255, 255,255, 200); /* Viền đỏ đậm */\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 100); /* Đổ bóng */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170,0,0); /* Màu sáng hơn khi hover */\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(112,0,0); /* Màu tối hơn khi nhấn */\n"
"    color: rgb(255,255,255);\n"
"    box-shadow: 1px 1px 5px rgba(0, 0, 0, 150); /* Giảm bóng khi nhấn */\n"
"}")
        self.pushButton_Home.setObjectName("pushButton_Home")
        self.horizontalLayout.addWidget(self.pushButton_Home)
        self.pushButton_AssignStudent = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_AssignStudent.setMaximumSize(QtCore.QSize(16777215, 45))
        self.pushButton_AssignStudent.setStyleSheet("QPushButton {\n"
"    font: 5000 14pt \"Arial\"; /* Font Arial Black, size 12 */\n"
"    background-color: rgba(255,255,255,100); /* Màu nền đỏ đậm */\n"
"    color: rgb(0,0,90); /* Màu chữ trắng */\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"    padding: 8px; /* Khoảng cách giữa chữ và viền */\n"
"    border: 4px solid rgba(255, 255,255, 200); /* Viền đỏ đậm */\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 100); /* Đổ bóng */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,0,90); /* Màu sáng hơn khi hover */\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0,9); /* Màu tối hơn khi nhấn */\n"
"    color: rgb(255,255,255);\n"
"    box-shadow: 1px 1px 5px rgba(0, 0, 0, 150); /* Giảm bóng khi nhấn */\n"
"}")
        self.pushButton_AssignStudent.setObjectName("pushButton_AssignStudent")
        self.horizontalLayout.addWidget(self.pushButton_AssignStudent)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(AddClassDialog)
        QtCore.QMetaObject.connectSlotsByName(AddClassDialog)

    def retranslateUi(self, AddClassDialog):
        _translate = QtCore.QCoreApplication.translate
        AddClassDialog.setWindowTitle(_translate("AddClassDialog", "Add Class"))
        self.label.setText(_translate("AddClassDialog", "ADD CLASS"))
        self.label_18.setText(_translate("AddClassDialog", "Class ID:"))
        self.label_19.setText(_translate("AddClassDialog", "Class Name:"))
        self.label_20.setText(_translate("AddClassDialog", "Subject:"))
        self.label_21.setText(_translate("AddClassDialog", "Major:"))
        self.label_22.setText(_translate("AddClassDialog", "Teacher:"))
        self.label_23.setText(_translate("AddClassDialog", "List of students:"))
        self.pushButton_AssignStudent_2.setText(_translate("AddClassDialog", "ASSIGN STUDENT FOR THIS CLASS"))
        self.pushButton_Home.setText(_translate("AddClassDialog", "HOME"))
        self.pushButton_AssignStudent.setText(_translate("AddClassDialog", "SAVE CLASS"))
