# Form implementation generated from reading ui file 'D:\Documents\KTLT\FinalTerm\ui\Admin\AddStudent.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AssignStudentsDialog(object):
    def setupUi(self, AssignStudentsDialog):
        AssignStudentsDialog.setObjectName("AssignStudentsDialog")
        AssignStudentsDialog.resize(1000, 600)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=AssignStudentsDialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 981, 581))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ComboBox_Class = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_2)
        self.ComboBox_Class.setMinimumSize(QtCore.QSize(0, 50))
        self.ComboBox_Class.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 25px; /* Bo tròn cả 4 góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 30px; /* Chừa khoảng trống bên phải */\n"
"}\n"
"\n"
"/* Ẩn nền của nút dropdown để bo góc phải */\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    background: transparent; /* Để nền trong suốt */\n"
"    width: 25px;\n"
"    subcontrol-position: right center;\n"
"}\n"
"\n"
"/* Tạo nền bo góc cho dropdown */\n"
"QComboBox::down-arrow {\n"
"    image: url(image/down-arrow.png);\n"
"    width: 10px;\n"
"    height: 12px;\n"
"    margin-right: 5px;\n"
"}\n"
"")
        self.ComboBox_Class.setObjectName("ComboBox_Class")
        self.verticalLayout_2.addWidget(self.ComboBox_Class)
        self.groupBox_SelectedStudent = QtWidgets.QGroupBox(parent=self.verticalLayoutWidget_2)
        self.groupBox_SelectedStudent.setStyleSheet("font: 2000 12pt \"Arial\";\n"
"color: rgb(0,0,90);")
        self.groupBox_SelectedStudent.setObjectName("groupBox_SelectedStudent")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.groupBox_SelectedStudent)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 961, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget_Students = QtWidgets.QListWidget(parent=self.verticalLayoutWidget)
        self.listWidget_Students.setMinimumSize(QtCore.QSize(0, 236))
        self.listWidget_Students.setMaximumSize(QtCore.QSize(16777215, 500))
        self.listWidget_Students.setStyleSheet("    QListWidget {\n"
"        border: 2px solid rgb(255,255,255);\n"
"        border-top-left-radius: 20px;  /* Bo góc trái trên */\n"
"        border-top-right-radius: 20px; /* Bo góc phải trên */\n"
"        border-bottom-left-radius: 0px;  /* Giữ góc dưới vuông */\n"
"        border-bottom-right-radius: 0px; /* Giữ góc dưới vuông */\n"
"        background-color: white;\n"
"        padding: 5px;\n"
"    }")
        self.listWidget_Students.setObjectName("listWidget_Students")
        self.verticalLayout.addWidget(self.listWidget_Students)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Home = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_Home.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_Home.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_Home.setStyleSheet("QPushButton {\n"
"    font: 5000 14pt \"Arial\"; /* Font Arial Black, size 12 */\n"
"    background-color: rgba(170,0,0,150); /* Màu nền đỏ đậm */\n"
"    color: rgb(255,255,255); /* Màu chữ trắng */\n"
"    border-bottom-left-radius: 20px;\n"
"    padding: 4px; /* Khoảng cách giữa chữ và viền */\n"
"    border: 4px solid rgba(255, 255,255, 200); /* Viền đỏ đậm */\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 100); /* Đổ bóng */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170,0,0); /* Màu sáng hơn khi hover */\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(112,0,0); /* Màu tối hơn khi nhấn */\n"
"    color: rgb(255,255,255);\n"
"    box-shadow: 1px 1px 5px rgba(0, 0, 0, 150); /* Giảm bóng khi nhấn */\n"
"}")
        self.pushButton_Home.setObjectName("pushButton_Home")
        self.horizontalLayout.addWidget(self.pushButton_Home)
        self.pushButton_AssignStudent = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_AssignStudent.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_AssignStudent.setStyleSheet("QPushButton {\n"
"    font: 5000 14pt \"Arial\"; /* Font Arial Black, size 12 */\n"
"    background-color: rgba(0,85,0,100); /* Màu nền đỏ đậm */\n"
"    color: rgb(0, 85, 0); /* Màu chữ trắng */\n"
"    border-bottom-right-radius: 20px;\n"
"    padding: 8px; /* Khoảng cách giữa chữ và viền */\n"
"    border: 4px solid rgba(255, 255,255, 200); /* Viền đỏ đậm */\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 100); /* Đổ bóng */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  rgb(0, 109, 80); /* Màu sáng hơn khi hover */\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0,85,0); /* Màu tối hơn khi nhấn */\n"
"    color: rgb(255,255,255);\n"
"    box-shadow: 1px 1px 5px rgba(0, 0, 0, 150); /* Giảm bóng khi nhấn */\n"
"}")
        self.pushButton_AssignStudent.setObjectName("pushButton_AssignStudent")
        self.horizontalLayout.addWidget(self.pushButton_AssignStudent)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox_SelectedStudent)

        self.retranslateUi(AssignStudentsDialog)
        QtCore.QMetaObject.connectSlotsByName(AssignStudentsDialog)

    def retranslateUi(self, AssignStudentsDialog):
        _translate = QtCore.QCoreApplication.translate
        AssignStudentsDialog.setWindowTitle(_translate("AssignStudentsDialog", "Assign Students"))
        self.groupBox_SelectedStudent.setTitle(_translate("AssignStudentsDialog", "SELECTED STUDENTS"))
        self.pushButton_Home.setText(_translate("AssignStudentsDialog", "BACK"))
        self.pushButton_AssignStudent.setText(_translate("AssignStudentsDialog", "SAVE"))
