# Form implementation generated from reading ui file 'D:\Documents\KTLT\FinalTerm\ui\Admin\CreateClass.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddClassDialog(object):
    def setupUi(self, AddClassDialog):
        AddClassDialog.setObjectName("AddClassDialog")
        AddClassDialog.resize(1000, 600)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=AddClassDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 981, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setStyleSheet("color: rgb(0, 0, 90);\n"
"font: 5000 22pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(7)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_18 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 55))
        self.label_18.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_12.addWidget(self.label_18)
        self.label_20 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 55))
        self.label_20.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_12.addWidget(self.label_20)
        self.label_22 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 55))
        self.label_22.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.label_22.setObjectName("label_22")
        self.verticalLayout_12.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 55))
        self.label_23.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_12.addWidget(self.label_23)
        self.label_19 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 55))
        self.label_19.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_12.addWidget(self.label_19)
        self.label_21 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 55))
        self.label_21.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_12.addWidget(self.label_21)
        self.horizontalLayout_2.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(7)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.lineEdit_ClassId = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ClassId.sizePolicy().hasHeightForWidth())
        self.lineEdit_ClassId.setSizePolicy(sizePolicy)
        self.lineEdit_ClassId.setMaximumSize(QtCore.QSize(16777215, 55))
        self.lineEdit_ClassId.setSizeIncrement(QtCore.QSize(0, 10))
        self.lineEdit_ClassId.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 20px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 20px; /* Chừa khoảng trống bên phải */\n"
"}")
        self.lineEdit_ClassId.setObjectName("lineEdit_ClassId")
        self.verticalLayout_13.addWidget(self.lineEdit_ClassId)
        self.lineEdit_Subject = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Subject.sizePolicy().hasHeightForWidth())
        self.lineEdit_Subject.setSizePolicy(sizePolicy)
        self.lineEdit_Subject.setMaximumSize(QtCore.QSize(16777215, 55))
        self.lineEdit_Subject.setSizeIncrement(QtCore.QSize(0, 10))
        self.lineEdit_Subject.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 20px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 20px; /* Chừa khoảng trống bên phải */\n"
"}")
        self.lineEdit_Subject.setObjectName("lineEdit_Subject")
        self.verticalLayout_13.addWidget(self.lineEdit_Subject)
        self.lineEdit_Teacher = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Teacher.sizePolicy().hasHeightForWidth())
        self.lineEdit_Teacher.setSizePolicy(sizePolicy)
        self.lineEdit_Teacher.setMaximumSize(QtCore.QSize(16777215, 55))
        self.lineEdit_Teacher.setSizeIncrement(QtCore.QSize(0, 10))
        self.lineEdit_Teacher.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 20px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 20px; /* Chừa khoảng trống bên phải */\n"
"}")
        self.lineEdit_Teacher.setObjectName("lineEdit_Teacher")
        self.verticalLayout_13.addWidget(self.lineEdit_Teacher)
        self.lineEdit_Schedule = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Schedule.sizePolicy().hasHeightForWidth())
        self.lineEdit_Schedule.setSizePolicy(sizePolicy)
        self.lineEdit_Schedule.setMaximumSize(QtCore.QSize(16777215, 55))
        self.lineEdit_Schedule.setSizeIncrement(QtCore.QSize(0, 10))
        self.lineEdit_Schedule.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 20px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 20px; /* Chừa khoảng trống bên phải */\n"
"}")
        self.lineEdit_Schedule.setObjectName("lineEdit_Schedule")
        self.verticalLayout_13.addWidget(self.lineEdit_Schedule)
        self.lineEdit_Room = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Room.sizePolicy().hasHeightForWidth())
        self.lineEdit_Room.setSizePolicy(sizePolicy)
        self.lineEdit_Room.setMaximumSize(QtCore.QSize(16777215, 55))
        self.lineEdit_Room.setSizeIncrement(QtCore.QSize(0, 10))
        self.lineEdit_Room.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 20px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 20px; /* Chừa khoảng trống bên phải */\n"
"}")
        self.lineEdit_Room.setObjectName("lineEdit_Room")
        self.verticalLayout_13.addWidget(self.lineEdit_Room)
        self.lineEdit_Major = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Major.sizePolicy().hasHeightForWidth())
        self.lineEdit_Major.setSizePolicy(sizePolicy)
        self.lineEdit_Major.setMaximumSize(QtCore.QSize(16777215, 55))
        self.lineEdit_Major.setSizeIncrement(QtCore.QSize(0, 10))
        self.lineEdit_Major.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 20px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 20px; /* Chừa khoảng trống bên phải */\n"
"}")
        self.lineEdit_Major.setObjectName("lineEdit_Major")
        self.verticalLayout_13.addWidget(self.lineEdit_Major)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Back = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_Back.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_Back.setMaximumSize(QtCore.QSize(16777215, 45))
        self.pushButton_Back.setStyleSheet("QPushButton {\n"
"    font: 5000 14pt \"Arial\"; /* Font Arial Black, size 12 */\n"
"    background-color: rgba(170,0,0,150); /* Màu nền đỏ đậm */\n"
"    color: rgb(255,255,255); /* Màu chữ trắng */\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    padding: 4px; /* Khoảng cách giữa chữ và viền */\n"
"    border: 4px solid rgba(255, 255,255, 200); /* Viền đỏ đậm */\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 100); /* Đổ bóng */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170,0,0); /* Màu sáng hơn khi hover */\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(112,0,0); /* Màu tối hơn khi nhấn */\n"
"    color: rgb(255,255,255);\n"
"    box-shadow: 1px 1px 5px rgba(0, 0, 0, 150); /* Giảm bóng khi nhấn */\n"
"}")
        self.pushButton_Back.setObjectName("pushButton_Back")
        self.horizontalLayout.addWidget(self.pushButton_Back)
        self.pushButton_SaveClass = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_SaveClass.setMaximumSize(QtCore.QSize(16777215, 45))
        self.pushButton_SaveClass.setStyleSheet("QPushButton {\n"
"    font: 5000 14pt \"Arial\"; /* Font Arial Black, size 12 */\n"
"    background-color: rgba(255,255,255,100); /* Màu nền đỏ đậm */\n"
"    color: rgb(0,0,90); /* Màu chữ trắng */\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"    padding: 8px; /* Khoảng cách giữa chữ và viền */\n"
"    border: 4px solid rgba(255, 255,255, 200); /* Viền đỏ đậm */\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 100); /* Đổ bóng */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,0,90); /* Màu sáng hơn khi hover */\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0,9); /* Màu tối hơn khi nhấn */\n"
"    color: rgb(255,255,255);\n"
"    box-shadow: 1px 1px 5px rgba(0, 0, 0, 150); /* Giảm bóng khi nhấn */\n"
"}")
        self.pushButton_SaveClass.setObjectName("pushButton_SaveClass")
        self.horizontalLayout.addWidget(self.pushButton_SaveClass)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(AddClassDialog)
        QtCore.QMetaObject.connectSlotsByName(AddClassDialog)

    def retranslateUi(self, AddClassDialog):
        _translate = QtCore.QCoreApplication.translate
        AddClassDialog.setWindowTitle(_translate("AddClassDialog", "Create a new class"))
        self.label.setText(_translate("AddClassDialog", "CREATE CLASS"))
        self.label_18.setText(_translate("AddClassDialog", "Class ID:"))
        self.label_20.setText(_translate("AddClassDialog", "Subject:"))
        self.label_22.setText(_translate("AddClassDialog", "Teacher:"))
        self.label_23.setText(_translate("AddClassDialog", "Schedule:"))
        self.label_19.setText(_translate("AddClassDialog", "Room:"))
        self.label_21.setText(_translate("AddClassDialog", "Major:"))
        self.pushButton_Back.setText(_translate("AddClassDialog", "BACK"))
        self.pushButton_SaveClass.setText(_translate("AddClassDialog", "SAVE CLASS"))
