# Form implementation generated from reading ui file 'D:\Documents\KTLT\FinalTerm\ui\Student\StudentMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 684)
        MainWindow.setMaximumSize(QtCore.QSize(1056, 752))
        MainWindow.setAutoFillBackground(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.scrollArea.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 790, 641))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.scrollAreaWidgetContents)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.stackedWidget.setMaximumSize(QtCore.QSize(933, 250))
        self.stackedWidget.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_2 = QtWidgets.QLabel(parent=self.page_2)
        self.label_2.setGeometry(QtCore.QRect(1, 0, 768, 51))
        self.label_2.setStyleSheet("background-color: white;\n"
"color: rgb(0, 0, 90);\n"
"font-weight: bold;\n"
"font: 5000 18pt \"Arial\";\n"
"    border-top-left-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    padding: 10px;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parent=self.page_2)
        self.label.setGeometry(QtCore.QRect(1, 20, 768, 281))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(1200, 350))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Documents\\KTLT\\FinalTerm\\ui\\Student\\../../../../../Downloads/TNT_7659-scaled(1)(1).png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextEditable)
        self.label.setObjectName("label")
        self.label.raise_()
        self.label_2.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.scrollAreaWidgetContents)
        self.tabWidget.setMinimumSize(QtCore.QSize(768, 320))
        self.tabWidget.setMaximumSize(QtCore.QSize(768, 320))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("/* Tab chưa được chọn */\n"
"QTabBar::tab {\n"
"    width:100px;\n"
"    min-height: 20px;  /* Đảm bảo đủ cao để hiển thị chữ */\n"
"    text-align: center;\n"
"    color: #00005A;  \n"
"    font: 2000 10pt \"Arial\";  \n"
"    padding: 6px 12px;  /* Khoảng cách hợp lý trong tab */\n"
"    border-top-left-radius: 12px;  \n"
"    border-top-right-radius: 12px;\n"
"    background: #EAEAEA;\n"
"}\n"
"\n"
"/* Tab được chọn */\n"
"QTabBar::tab:selected {\n"
"    background: white;\n"
"    color: #00008B;\n"
"    text-align: center;\n"
"}\n"
"\n"
"\n"
"/* Đảm bảo tab cuối không dài hơn */\n"
"QTabBar::tab:last {\n"
"    width: 250px; /* Giới hạn chiều dài */\n"
"    text-align: center;\n"
"}\n"
"QTabWidget:{\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_score = QtWidgets.QWidget()
        self.tab_score.setObjectName("tab_score")
        self.frame = QtWidgets.QFrame(parent=self.tab_score)
        self.frame.setGeometry(QtCore.QRect(0, 0, 768, 256))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.table_grade = QtWidgets.QTableWidget(parent=self.frame)
        self.table_grade.setGeometry(QtCore.QRect(0, 30, 768, 226))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_grade.sizePolicy().hasHeightForWidth())
        self.table_grade.setSizePolicy(sizePolicy)
        self.table_grade.setMinimumSize(QtCore.QSize(768, 0))
        self.table_grade.setMaximumSize(QtCore.QSize(768, 16777215))
        self.table_grade.setMouseTracking(False)
        self.table_grade.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.table_grade.setStyleSheet("/* Header trên cùng */\n"
"QHeaderView::section {\n"
"    background: rgb(255,255,255);  /* Màu xanh đậm */\n"
"    color: rgb(0,0,90);  /* Chữ trắng */\n"
"    font: 2000 12px \"Arial\";\n"
"}\n"
"QTableWidget:{\n"
"    background-color: rgb(255,255,255);\n"
"    color: rgb(0,0,0);  /* Chữ trắng */\n"
"    border: 1px solid grey;  /* Viền trắng nhẹ */\n"
"    font: 2000 12px \"Arial\";\n"
"}\n"
"")
        self.table_grade.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.table_grade.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.table_grade.setAutoScrollMargin(16)
        self.table_grade.setColumnCount(6)
        self.table_grade.setObjectName("table_grade")
        self.table_grade.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        item.setFont(font)
        self.table_grade.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_grade.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_grade.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_grade.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_grade.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_grade.setHorizontalHeaderItem(5, item)
        self.table_grade.horizontalHeader().setCascadingSectionResizes(True)
        self.table_grade.horizontalHeader().setDefaultSectionSize(170)
        self.table_grade.horizontalHeader().setSortIndicatorShown(True)
        self.table_grade.horizontalHeader().setStretchLastSection(True)
        self.table_grade.verticalHeader().setCascadingSectionResizes(True)
        self.ComboBox_semester = QtWidgets.QComboBox(parent=self.frame)
        self.ComboBox_semester.setEnabled(False)
        self.ComboBox_semester.setGeometry(QtCore.QRect(0, 0, 768, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_semester.sizePolicy().hasHeightForWidth())
        self.ComboBox_semester.setSizePolicy(sizePolicy)
        self.ComboBox_semester.setMinimumSize(QtCore.QSize(768, 30))
        self.ComboBox_semester.setMaximumSize(QtCore.QSize(768, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(99)
        self.ComboBox_semester.setFont(font)
        self.ComboBox_semester.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.ComboBox_semester.setStyleSheet("QComboBox {\n"
"    background-color: navy;\n"
"    color: white;\n"
"    font: 2000 14px \"Arial\";\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}")
        self.ComboBox_semester.setEditable(False)
        self.ComboBox_semester.setFrame(False)
        self.ComboBox_semester.setObjectName("ComboBox_semester")
        self.ComboBox_semester.addItem("")
        self.ComboBox_semester.addItem("")
        self.ComboBox_semester.addItem("")
        self.ComboBox_semester.addItem("")
        self.ComboBox_semester.addItem("")
        self.ComboBox_semester.addItem("")
        self.ComboBox_semester.addItem("")
        self.ComboBox_semester.addItem("")
        self.ComboBox_semester.addItem("")
        self.pushButton_updatecore = QtWidgets.QPushButton(parent=self.tab_score)
        self.pushButton_updatecore.setGeometry(QtCore.QRect(0, 255, 768, 30))
        self.pushButton_updatecore.setMinimumSize(QtCore.QSize(768, 30))
        self.pushButton_updatecore.setMaximumSize(QtCore.QSize(768, 30))
        self.pushButton_updatecore.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0,0,90);\n"
"font: 2000 10pt \"Arial\";\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-left-radius: 15px;\n"
"    border-bottom-right-radius: 15px;")
        self.pushButton_updatecore.setObjectName("pushButton_updatecore")
        self.tabWidget.addTab(self.tab_score, "")
        self.tab_schedule = QtWidgets.QWidget()
        self.tab_schedule.setObjectName("tab_schedule")
        self.scrollArea_4 = QtWidgets.QScrollArea(parent=self.tab_schedule)
        self.scrollArea_4.setGeometry(QtCore.QRect(0, 0, 768, 286))
        self.scrollArea_4.setMinimumSize(QtCore.QSize(768, 0))
        self.scrollArea_4.setMaximumSize(QtCore.QSize(768, 16777215))
        self.scrollArea_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 768, 286))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents_4)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 751, 261))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listWidget_schedule = QtWidgets.QListWidget(parent=self.verticalLayoutWidget_3)
        self.listWidget_schedule.setObjectName("listWidget_schedule")
        self.verticalLayout_5.addWidget(self.listWidget_schedule)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.tabWidget.addTab(self.tab_schedule, "")
        self.tab_notice = QtWidgets.QWidget()
        self.tab_notice.setObjectName("tab_notice")
        self.scrollArea_5 = QtWidgets.QScrollArea(parent=self.tab_notice)
        self.scrollArea_5.setGeometry(QtCore.QRect(0, 0, 768, 286))
        self.scrollArea_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 768, 286))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents_5)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 751, 261))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.listWidget_notice = QtWidgets.QListWidget(parent=self.verticalLayoutWidget_5)
        self.listWidget_notice.setObjectName("listWidget_notice")
        self.verticalLayout_7.addWidget(self.listWidget_notice)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.tabWidget.addTab(self.tab_notice, "")
        self.tab_inforstudent = QtWidgets.QWidget()
        self.tab_inforstudent.setMinimumSize(QtCore.QSize(768, 0))
        self.tab_inforstudent.setMaximumSize(QtCore.QSize(768, 16777215))
        self.tab_inforstudent.setObjectName("tab_inforstudent")
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.tab_inforstudent)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 0, 768, 286))
        self.scrollArea_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 768, 286))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(120, 10, 221, 261))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_id = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_4)
        self.lineEdit_id.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lineEdit_id.setSizeIncrement(QtCore.QSize(0, 10))
        self.lineEdit_id.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 20px; /* Chừa khoảng trống bên phải */\n"
"}")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.verticalLayout_6.addWidget(self.lineEdit_id)
        self.lineEdit_fullname = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_4)
        self.lineEdit_fullname.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lineEdit_fullname.setSizeIncrement(QtCore.QSize(0, 10))
        self.lineEdit_fullname.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 20px; /* Chừa khoảng trống bên phải */\n"
"}")
        self.lineEdit_fullname.setObjectName("lineEdit_fullname")
        self.verticalLayout_6.addWidget(self.lineEdit_fullname)
        self.dateEdit_bir = QtWidgets.QDateEdit(parent=self.verticalLayoutWidget_4)
        self.dateEdit_bir.setMaximumSize(QtCore.QSize(16777215, 40))
        self.dateEdit_bir.setSizeIncrement(QtCore.QSize(0, 10))
        self.dateEdit_bir.setStyleSheet("QDateEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 20px; /* Chừa khoảng trống bên phải */\n"
"}\n"
"\n"
"QDateEdit::up-button {\n"
"    image: url(image/up-arrow.png);\n"
"    width: 10px;\n"
"    height: 12px;\n"
"    border: none;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right; /* Giữ vị trí */\n"
"    margin-right: 10px; /* Giảm khoảng cách */\n"
"    margin-top: 6px;\n"
"}\n"
"\n"
"QDateEdit::down-button {\n"
"    image: url(image/down-arrow.png);\n"
"    width: 10px;\n"
"    height: 12px;\n"
"    border: none;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right; /* Giữ vị trí */\n"
"    margin-right: 10px; /* Giảm khoảng cách */\n"
"    margin-bottom: 6px;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    border: none;\n"
"} \n"
"")
        self.dateEdit_bir.setObjectName("dateEdit_bir")
        self.verticalLayout_6.addWidget(self.dateEdit_bir)
        self.comboBox_gender = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_4)
        self.comboBox_gender.setMaximumSize(QtCore.QSize(16777215, 40))
        self.comboBox_gender.setSizeIncrement(QtCore.QSize(0, 10))
        self.comboBox_gender.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 15px; /* Bo tròn cả 4 góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 30px; /* Chừa khoảng trống bên phải */\n"
"}\n"
"\n"
"/* Ẩn nền của nút dropdown để bo góc phải */\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    background: transparent; /* Để nền trong suốt */\n"
"    width: 25px;\n"
"    subcontrol-position: right center;\n"
"}\n"
"\n"
"/* Tạo nền bo góc cho dropdown */\n"
"QComboBox::down-arrow {\n"
"    image: url(image/down-arrow.png);\n"
"    width: 10px;\n"
"    height: 12px;\n"
"    margin-right: 5px;\n"
"}\n"
"")
        self.comboBox_gender.setObjectName("comboBox_gender")
        self.comboBox_gender.addItem("")
        self.comboBox_gender.addItem("")
        self.verticalLayout_6.addWidget(self.comboBox_gender)
        self.lineEdit_mail = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_4)
        self.lineEdit_mail.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lineEdit_mail.setSizeIncrement(QtCore.QSize(0, 10))
        self.lineEdit_mail.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 20px; /* Chừa khoảng trống bên phải */\n"
"}")
        self.lineEdit_mail.setObjectName("lineEdit_mail")
        self.verticalLayout_6.addWidget(self.lineEdit_mail)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(20, 10, 93, 261))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_6)
        self.label_6.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_6)
        self.label_5.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_6)
        self.label_4.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.label_7 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_6)
        self.label_7.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_6)
        self.label_3.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(350, 10, 401, 261))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setHorizontalSpacing(7)
        self.formLayout_2.setVerticalSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.khAHCLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.khAHCLabel.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.khAHCLabel.setObjectName("khAHCLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.khAHCLabel)
        self.LineEdit_course = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.LineEdit_course.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 20px; /* Chừa khoảng trống bên phải */\n"
"}")
        self.LineEdit_course.setObjectName("LineEdit_course")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LineEdit_course)
        self.ngNhLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.ngNhLabel.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.ngNhLabel.setObjectName("ngNhLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.ngNhLabel)
        self.LineEdit_major = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.LineEdit_major.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 20px; /* Chừa khoảng trống bên phải */\n"
"}")
        self.LineEdit_major.setObjectName("LineEdit_major")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LineEdit_major)
        self.lPLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lPLabel.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.lPLabel.setObjectName("lPLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lPLabel)
        self.LineEdit_class = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.LineEdit_class.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 20px; /* Chừa khoảng trống bên phải */\n"
"}")
        self.LineEdit_class.setObjectName("LineEdit_class")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LineEdit_class)
        self.cVNHCTPLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.cVNHCTPLabel.setStyleSheet("font: 1000 10pt \"Cambria\";")
        self.cVNHCTPLabel.setObjectName("cVNHCTPLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.cVNHCTPLabel)
        self.LineEdit_advisor = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.LineEdit_advisor.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font: 500 15px \"Cambria\";\n"
"    background: white;\n"
"    padding-right: 20px; /* Chừa khoảng trống bên phải */\n"
"}")
        self.LineEdit_advisor.setObjectName("LineEdit_advisor")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LineEdit_advisor)
        self.pushButton_updateinfo = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.pushButton_updateinfo.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_updateinfo.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_updateinfo.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"background-color: rgb(0,0,90);\n"
"font: 2000 14pt \"Arial\";")
        self.pushButton_updateinfo.setObjectName("pushButton_updateinfo")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pushButton_updateinfo)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.addTab(self.tab_inforstudent, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_exit = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_exit.sizePolicy().hasHeightForWidth())
        self.pushButton_exit.setSizePolicy(sizePolicy)
        self.pushButton_exit.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_exit.setMaximumSize(QtCore.QSize(400, 50))
        self.pushButton_exit.setSizeIncrement(QtCore.QSize(0, 500))
        self.pushButton_exit.setStyleSheet("QPushButton {\n"
"    font: 5000 14pt \"Arial\"; /* Font Arial Black, size 12 */\n"
"    background-color: rgba(170,0,0,150); /* Màu nền đỏ đậm */\n"
"    color: rgb(255,255,255); /* Màu chữ trắng */\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    padding: 8px; /* Khoảng cách giữa chữ và viền */\n"
"    border: 4px solid rgba(255, 255,255, 200); /* Viền đỏ đậm */\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 100); /* Đổ bóng */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170,0,0); /* Màu sáng hơn khi hover */\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(112,0,0); /* Màu tối hơn khi nhấn */\n"
"    color: rgb(255,255,255);\n"
"    box-shadow: 1px 1px 5px rgba(0, 0, 0, 150); /* Giảm bóng khi nhấn */\n"
"}")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.horizontalLayout.addWidget(self.pushButton_exit)
        self.pushButton_logout = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_logout.sizePolicy().hasHeightForWidth())
        self.pushButton_logout.setSizePolicy(sizePolicy)
        self.pushButton_logout.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_logout.setMaximumSize(QtCore.QSize(400, 50))
        self.pushButton_logout.setStyleSheet("QPushButton {\n"
"    font: 5000 14pt \"Arial\"; /* Font Arial Black, size 12 */\n"
"    background-color: rgba(255,255,255,100); /* Màu nền đỏ đậm */\n"
"    color: rgb(0,0,90); /* Màu chữ trắng */\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"    padding: 8px; /* Khoảng cách giữa chữ và viền */\n"
"    border: 4px solid rgba(255, 255,255, 200); /* Viền đỏ đậm */\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 100); /* Đổ bóng */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,0,90); /* Màu sáng hơn khi hover */\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0,9); /* Màu tối hơn khi nhấn */\n"
"    color: rgb(255,255,255);\n"
"    box-shadow: 1px 1px 5px rgba(0, 0, 0, 150); /* Giảm bóng khi nhấn */\n"
"}")
        self.pushButton_logout.setIconSize(QtCore.QSize(50, 20))
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.horizontalLayout.addWidget(self.pushButton_logout)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(2)
        self.ComboBox_semester.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "STUDENT"))
        item = self.table_grade.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "SUBJECTS"))
        item = self.table_grade.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FORMATIVE SCORE 1"))
        item = self.table_grade.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "FORMATIVE SCORE 2"))
        item = self.table_grade.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "MIDTERM"))
        item = self.table_grade.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "FINALTERM"))
        item = self.table_grade.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "AVERAGE"))
        self.ComboBox_semester.setItemText(0, _translate("MainWindow", "     SEMESTER 1"))
        self.ComboBox_semester.setItemText(1, _translate("MainWindow", "     SEMESTER 2"))
        self.ComboBox_semester.setItemText(2, _translate("MainWindow", "     SEMESTER 3"))
        self.ComboBox_semester.setItemText(3, _translate("MainWindow", "     SEMESTER 4"))
        self.ComboBox_semester.setItemText(4, _translate("MainWindow", "     SEMESTER 5"))
        self.ComboBox_semester.setItemText(5, _translate("MainWindow", "     SEMESTER 6"))
        self.ComboBox_semester.setItemText(6, _translate("MainWindow", "     SEMESTER 7"))
        self.ComboBox_semester.setItemText(7, _translate("MainWindow", "     SEMESTER 8"))
        self.ComboBox_semester.setItemText(8, _translate("MainWindow", "     SEMESTER 9"))
        self.pushButton_updatecore.setText(_translate("MainWindow", "UPDATE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_score), _translate("MainWindow", "SCORE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_schedule), _translate("MainWindow", "SCHEDULE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_notice), _translate("MainWindow", "NOTICE"))
        self.comboBox_gender.setItemText(0, _translate("MainWindow", "Male"))
        self.comboBox_gender.setItemText(1, _translate("MainWindow", "Female"))
        self.label_6.setText(_translate("MainWindow", "Student ID:"))
        self.label_5.setText(_translate("MainWindow", "Full Name:"))
        self.label_4.setText(_translate("MainWindow", "Birthday:"))
        self.label_7.setText(_translate("MainWindow", "Gender:"))
        self.label_3.setText(_translate("MainWindow", "Email:"))
        self.khAHCLabel.setText(_translate("MainWindow", "Course:"))
        self.ngNhLabel.setText(_translate("MainWindow", "Major:"))
        self.lPLabel.setText(_translate("MainWindow", "Class:"))
        self.cVNHCTPLabel.setText(_translate("MainWindow", "Academic Advisor:"))
        self.pushButton_updateinfo.setText(_translate("MainWindow", "UPDATE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_inforstudent), _translate("MainWindow", "PERSONAL INFORMATION"))
        self.pushButton_exit.setText(_translate("MainWindow", "EXIT"))
        self.pushButton_logout.setText(_translate("MainWindow", "LOGOUT"))
