# Form implementation generated from reading ui file 'D:\Documents\KTLT\FinalTerm\ui\Teacher\inputgrade.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 712)
        MainWindow.setMaximumSize(QtCore.QSize(10000, 10000))
        MainWindow.setAutoFillBackground(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1000, 712))
        self.label.setStyleSheet("/* Header trên cùng */\n"
"QHeaderView::section {\n"
"    background: rgb(255,255,255);  /* Màu xanh đậm */\n"
"    color: rgb(0,0,90);  /* Chữ trắng */\n"
"    font: 2000 12px \"Arial\";\n"
"}\n"
"\n"
"")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Documents\\KTLT\\FinalTerm\\ui\\Teacher\\../../image/55656.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(52, 56, 895, 600))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.scrollArea.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 895, 600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_class = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.lineEdit_class.setStyleSheet("    border: 1px solid gray;\n"
"\n"
"background-color: white;\n"
"color: rgb(0, 0, 90);\n"
"font-weight: bold;\n"
"font: 2000 18pt \"Cambria\";\n"
"\n"
"    border-top-left-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    padding: 10px;\n"
"")
        self.lineEdit_class.setObjectName("lineEdit_class")
        self.verticalLayout_3.addWidget(self.lineEdit_class)
        self.tableWidget_grade = QtWidgets.QTableWidget(parent=self.scrollAreaWidgetContents)
        self.tableWidget_grade.setMaximumSize(QtCore.QSize(16777215, 550))
        self.tableWidget_grade.setStyleSheet("/* === Bảng chính (QTableWidget) === */\n"
"QTableWidget {\n"
"    gridline-color: #000000; /* Màu đường kẻ ô */\n"
"    font: 2000 12px \"Arial\"; /* Kích thước chữ */\n"
"    background-color: white; /* Nền trắng */\n"
"    border: none; /* Xóa viền thừa */\n"
"    border-bottom-left-radius: 20px;  /* Bo góc dưới */\n"
"    border-bottom-right-radius: 20px;\n"
"}\n"
"\n"
"/* === Header (Dòng tiêu đề) === */\n"
"QHeaderView::section {\n"
"    background-color: navy; /* Màu nền tiêu đề */\n"
"    color: white; /* Màu chữ tiêu đề */\n"
"    border: 1px solid white; /* Viền trắng để tách cột */\n"
"    font: 2000 12px \"Arial\";\n"
"    padding: 6px; /* Khoảng cách chữ trong header */\n"
"}\n"
"\n"
"/* === Thanh cuộn dọc === */\n"
"QTableWidget::verticalScrollBar {\n"
"    width: 6px;  /* Độ rộng nhỏ hơn */\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 6px;  /* Làm thanh nhỏ */\n"
"    margin: 15px 0px 15px 0px; /* Tạo khoảng cách với mép */\n"
"}\n"
"\n"
"/* Thanh trượt (cái phần kéo được) */\n"
"QScrollBar::handle:vertical {\n"
"    background: #909090;  /* Màu trung tính */\n"
"    min-height: 30px;  /* Đảm bảo không quá nhỏ */\n"
"    border-radius: 3px;  /* Bo góc */\n"
"}\n"
"\n"
"/* Khi hover vào thanh kéo */\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #707070; /* Đổi màu tối hơn chút */\n"
"}\n"
"\n"
"/* Ẩn nút mũi tên trên/dưới */\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"    height: 0px;\n"
"}\n"
"\n"
"/* === Thanh cuộn ngang === */\n"
"QTableWidget::horizontalScrollBar {\n"
"    height: 6px;  /* Mỏng hơn */\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 6px;  \n"
"    margin: 0px 15px 0px 15px;\n"
"}\n"
"\n"
"/* Thanh trượt ngang */\n"
"QScrollBar::handle:horizontal {\n"
"    background: #909090;\n"
"    min-width: 30px;\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #707070;\n"
"}\n"
"\n"
"/* Ẩn góc giao giữa 2 thanh kéo */\n"
"QScrollBar::corner {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.tableWidget_grade.setObjectName("tableWidget_grade")
        self.tableWidget_grade.setColumnCount(7)
        self.tableWidget_grade.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_grade.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_grade.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_grade.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_grade.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_grade.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_grade.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_grade.setHorizontalHeaderItem(6, item)
        self.tableWidget_grade.horizontalHeader().setDefaultSectionSize(155)
        self.tableWidget_grade.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_grade.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget_grade.verticalHeader().setMinimumSectionSize(50)
        self.verticalLayout_3.addWidget(self.tableWidget_grade)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_home = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_home.sizePolicy().hasHeightForWidth())
        self.pushButton_home.setSizePolicy(sizePolicy)
        self.pushButton_home.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_home.setMaximumSize(QtCore.QSize(300, 60))
        self.pushButton_home.setSizeIncrement(QtCore.QSize(0, 500))
        self.pushButton_home.setStyleSheet("QPushButton {\n"
"    font: 5000 14pt \"Arial\"; /* Font Arial Black, size 12 */\n"
"    background-color: rgba(170,0,0,150); /* Màu nền đỏ đậm */\n"
"    color: rgb(255,255,255); /* Màu chữ trắng */\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    padding: 8px; /* Khoảng cách giữa chữ và viền */\n"
"    border: 4px solid rgba(255, 255,255, 200); /* Viền đỏ đậm */\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 100); /* Đổ bóng */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170,0,0); /* Màu sáng hơn khi hover */\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(112,0,0); /* Màu tối hơn khi nhấn */\n"
"    color: rgb(255,255,255);\n"
"    box-shadow: 1px 1px 5px rgba(0, 0, 0, 150); /* Giảm bóng khi nhấn */\n"
"}")
        self.pushButton_home.setObjectName("pushButton_home")
        self.horizontalLayout.addWidget(self.pushButton_home)
        self.pushButton_save = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save.sizePolicy().hasHeightForWidth())
        self.pushButton_save.setSizePolicy(sizePolicy)
        self.pushButton_save.setMaximumSize(QtCore.QSize(1000, 60))
        self.pushButton_save.setStyleSheet("QPushButton {\n"
"    font: 5000 14pt \"Arial\"; /* Font Arial Black, size 12 */\n"
"    background-color: rgba(0,85,0,100); /* Màu nền đỏ đậm */\n"
"    color: rgb(0, 85, 0); /* Màu chữ trắng */\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    padding: 8px; /* Khoảng cách giữa chữ và viền */\n"
"    border: 4px solid rgba(255, 255,255, 200); /* Viền đỏ đậm */\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 100); /* Đổ bóng */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  rgb(0, 109, 80); /* Màu sáng hơn khi hover */\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0,85,0); /* Màu tối hơn khi nhấn */\n"
"    color: rgb(255,255,255);\n"
"    box-shadow: 1px 1px 5px rgba(0, 0, 0, 150); /* Giảm bóng khi nhấn */\n"
"}")
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.pushButton_logout = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_logout.sizePolicy().hasHeightForWidth())
        self.pushButton_logout.setSizePolicy(sizePolicy)
        self.pushButton_logout.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_logout.setMaximumSize(QtCore.QSize(300, 60))
        self.pushButton_logout.setStyleSheet("QPushButton {\n"
"    font: 5000 14pt \"Arial\"; /* Font Arial Black, size 12 */\n"
"    background-color: rgba(255,255,255,100); /* Màu nền đỏ đậm */\n"
"    color: rgb(0,0,90); /* Màu chữ trắng */\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"    padding: 8px; /* Khoảng cách giữa chữ và viền */\n"
"    border: 4px solid rgba(255, 255,255, 200); /* Viền đỏ đậm */\n"
"    box-shadow: 3px 3px 8px rgba(0, 0, 0, 100); /* Đổ bóng */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,0,90); /* Màu sáng hơn khi hover */\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0,9); /* Màu tối hơn khi nhấn */\n"
"    color: rgb(255,255,255);\n"
"    box-shadow: 1px 1px 5px rgba(0, 0, 0, 150); /* Giảm bóng khi nhấn */\n"
"}")
        self.pushButton_logout.setIconSize(QtCore.QSize(50, 20))
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.horizontalLayout.addWidget(self.pushButton_logout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget_grade.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID STUDENT"))
        item = self.tableWidget_grade.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FULLNAME"))
        item = self.tableWidget_grade.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "FORMATIVE SCORE 1"))
        item = self.tableWidget_grade.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "FORMATIVE SCORE 2"))
        item = self.tableWidget_grade.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "MIDTERM"))
        item = self.tableWidget_grade.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "FINALTERM"))
        item = self.tableWidget_grade.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "AVERAGE"))
        self.pushButton_home.setText(_translate("MainWindow", "HOME"))
        self.pushButton_save.setText(_translate("MainWindow", "SAVE"))
        self.pushButton_logout.setText(_translate("MainWindow", "LOGOUT"))
