# Form implementation generated from reading ui file 'D:\Documents\KTLT\FinalTerm\ui\LoginMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(561, 463)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgba(170,0,0,100);\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 561, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font: 87 25pt \"Arial Black\";\n"
"background-color: rgb(255, 255, 255,0);\n"
"color: rgb(255,255,255);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 140, 521, 51))
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 25px; /* Bo góc 10px */\n"
"    padding: 5px; /* Tạo khoảng cách bên trong */\n"
"    padding-left: 60px; /* Đẩy chữ vào bên phải để icon che phía trước */\n"
"    background-color: rgb(255,255,255); /* Màu nền đỏ đậm */\n"
"}")
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 240, 521, 51))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 25px; /* Bo góc 10px */\n"
"    padding: 5px; /* Tạo khoảng cách bên trong */\n"
"    padding-left: 60px; /* Đẩy chữ vào bên phải để icon che phía trước */\n"
"    background-color: rgb(255,255,255); /* Màu nền đỏ đậm */\n"
"}")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 81, 20))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 210, 81, 20))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255,0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(32, 146, 30, 33))
        self.label_4.setStyleSheet("background-color: rgba(170, 0, 0,0);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:\\Documents\\KTLT\\FinalTerm\\ui\\../../../../Downloads/Screenshot_2025-02-26_180616-removebg-preview.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(29, 248, 37, 33))
        self.label_5.setStyleSheet("background-color: rgba(170, 0, 0,0);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:\\Documents\\KTLT\\FinalTerm\\ui\\../../../../Downloads/Screenshot_2025-02-26_173531-removebg-preview.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(20, 310, 251, 21))
        self.checkBox.setStyleSheet("color: rgb(0,0,0);\n"
"background-color: rgba(255, 255, 255,0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(400, 300, 141, 41))
        self.pushButton.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"text-decoration: underline;\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 350, 521, 41))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    font: 12pt \"Arial Black\"; /* Đặt font Arial Black, size 10 */\n"
"    background-color: rgb(170, 0, 0); /* Màu nền đỏ đậm */\n"
"    color: white; /* Màu chữ trắng */\n"
"    border-radius: 20px; /* Bo góc 10px */\n"
"    padding: 5px; /* Khoảng cách giữa chữ và viền */\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 561, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LoginMainWindow"))
        self.label.setText(_translate("MainWindow", "LOGIN"))
        self.label_2.setText(_translate("MainWindow", "Username:"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.checkBox.setText(_translate("MainWindow", "Save my login information"))
        self.pushButton.setText(_translate("MainWindow", "Forget password ?"))
        self.pushButton_2.setText(_translate("MainWindow", "LOGIN"))
